### ISSUE TITLE
Use File::Which to find pandoc executable?

### ISSUE THREAD

**Issue by nichtich** [nichtich/Pandoc-Wrapper#1]
This may work better on Windows and allow configuration of executable location.

**Comment by nichtich** [comment]
The module has not been tested on Windows at all.

**Comment by bpj** [comment]
I have a branch which allows specifying the executable path either in the import statement or per object. It introduces somewhat heavy changes to the import function and the constructor in particular though. Basically it makes the constructor or the import take a hashref with parameters, the currently recognised ones being `pandoc_version` and `pandoc_path`. You can still specify the version as a bare number if you like (although I wonder whether that may clash with specifying the module version?)

I can make it use File::Which and push it to my branch later today if you want to look at it. I might even be able to persuade my son to let me install perl, pandoc etc. on his Windows box for testing. I even have a Win 7 partition on one of my own machines although it was _very_ long since I booted it, so it would likely install updates for hours :-)

**Comment by nichtich** [comment]
Thanks for the input! I thought about the different approaches and implemented a slightly different way in 0.3.0! For now I think that this module is rather complete in terms of functionality.
